// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDczlsXm80eAQdSpN03zQuTarEgemoDnqA',
    appId: '1:744116559284:web:12bed3aa57bdb3be6366e1',
    messagingSenderId: '744116559284',
    projectId: 'laza-ecommerce-e774a',
    authDomain: 'laza-ecommerce-e774a.firebaseapp.com',
    storageBucket: 'laza-ecommerce-e774a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZKjI4h5YN32rKGS-icwaDa00yqVf3HQ',
    appId: '1:744116559284:android:0c5d115f1236561f6366e1',
    messagingSenderId: '744116559284',
    projectId: 'laza-ecommerce-e774a',
    storageBucket: 'laza-ecommerce-e774a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfDval7ZJqx3841zdCzQzsaiP1ZZ2274Y',
    appId: '1:744116559284:ios:faa6d85dcc2a3d096366e1',
    messagingSenderId: '744116559284',
    projectId: 'laza-ecommerce-e774a',
    storageBucket: 'laza-ecommerce-e774a.firebasestorage.app',
    iosBundleId: 'com.example.lazaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfDval7ZJqx3841zdCzQzsaiP1ZZ2274Y',
    appId: '1:744116559284:ios:faa6d85dcc2a3d096366e1',
    messagingSenderId: '744116559284',
    projectId: 'laza-ecommerce-e774a',
    storageBucket: 'laza-ecommerce-e774a.firebasestorage.app',
    iosBundleId: 'com.example.lazaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDczlsXm80eAQdSpN03zQuTarEgemoDnqA',
    appId: '1:744116559284:web:21c35b2473ca03176366e1',
    messagingSenderId: '744116559284',
    projectId: 'laza-ecommerce-e774a',
    authDomain: 'laza-ecommerce-e774a.firebaseapp.com',
    storageBucket: 'laza-ecommerce-e774a.firebasestorage.app',
  );
}
